# Starter pipeline

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'

  - script: pip install -e .
    displayName: 'Install requirements'

  - script: mkdir -p /tmp
    displayName: 'Create temp directory'

#  - script: |
#      python -m unittest discover -v
#    displayName: 'Run tests'

  - script: |
      pip install pytest
      pip install pytest-cov
      pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    displayName: 'Test with pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

  - script: 'python setup.py sdist'
    displayName: 'Build sdist'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: dist'
    inputs:
      pathtoPublish: 'dist'
      artifactName: 'dist'
