# Starter pipeline

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'Ubuntu 18.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
  - task: Bash@3
    displayName: 'Run bash'
    inputs:
      targetType: 'inline'
      script: |
        pip install -e .
        
        mkdir -p /tmp
        
        pip install pytest
        pip install pytest-cov
        pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
  - task: Bash@3
    displayName: 'Build sdist'
    inputs:
      targetType: 'inline'
      script: |
        python setup.py sdist
        echo "Current dir: $( pwd )"
        echo "######################"
        ls -als ./dist
        echo "##vso[task.setvariable variable=backupScriptReleaseVersion]$( python setup.py --version )"
  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'
    inputs:
      gitHubConnection: chgeuer
      repositoryName: chgeuer/python_backup
      tagSource: manual
      isPreRelease: true
      tag: $(backupScriptReleaseVersion)
      assets: |
          dist/asebackupcli-$(backupScriptReleaseVersion).tar.gz
